services:
    newscoop_ingest_plugin.lifecyclesubscriber:
        class: Newscoop\IngestPluginBundle\EventListener\LifecycleSubscriber
        arguments:
            - @em
        tags:
            - { name: kernel.event_subscriber}

    newscoop_ingest_plugin.configure_menu_listener:
        class: Newscoop\IngestPluginBundle\EventListener\ConfigureMenuListener
        tags:
            - { name: kernel.event_listener, event: newscoop_newscoop.menu_configure, method: onMenuConfigure }
        arguments:
            - @translator

    ingest.ingest:
        class:      Newscoop\IngestPluginBundle\Services\IngestService
        arguments:  ["@em"]

    ingest.publisher:
        class:      Newscoop\IngestPluginBundle\Services\PublishService
        arguments:  ["@em"]